---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes 

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes 

- name: "Install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2 package"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create app directory"
  become: true
  ansible.builtin.file:
    path: /home/ubuntu/backend
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: "Copy backend artifact file"
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "unzip artifacts"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Executing backend node"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm install    
    pm2 stop default
    pm2 start npm -- start

...