---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes 

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes 

- name: "Install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2 package"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Create app directory"
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory    

- name: "Copy backend artifact file"
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "unzip artifacts"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm install

- name: "Executing backend node app with PM2"  
  shell: |
    cd /home/ubuntu/backend/dist    
    pm2 stop default
    pm2 start main.js
    register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save

...